=== OrestNalyvaiko/task_xml/src/main/resources/banksXSD.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace="https://www.w3schools.com"
  xmlns="https://www.w3schools.com"
  elementFormDefault="qualified">

  <xs:element name="banks">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="bank" type="bankType" minOccurs="0"
          maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="bankType">
    <xs:sequence>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="country" type="xs:string"/>
      <xs:element name="type">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="to the question"/>
            <xs:enumeration value="urgent"/>
            <xs:enumeration value="calculated"/>
            <xs:enumeration value="cumulative"/>
            <xs:enumeration value="savings"/>
            <xs:enumeration value="metal"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="depositor" type="xs:string"/>
      <xs:element name="accountID">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:pattern
              value="[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="amountOnDeposit">
        <xs:simpleType>
          <xs:restriction base="xs:decimal">
            <xs:minExclusive value="0"/>
            <xs:fractionDigits value="2"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="profitability">
        <xs:simpleType>
          <xs:restriction base="xs:decimal">
            <xs:minExclusive value="0"/>
            <xs:maxExclusive value="20"/>
            <xs:fractionDigits value="1"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="timeConstraints">
        <xs:simpleType>
          <xs:restriction base="xs:integer">
            <xs:minExclusive value="0"/>
            <xs:maxExclusive value="15"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== OrestNalyvaiko/task_xml/src/main/resources/bankDeposits.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="banksXSLT.xsl"?>


<banks xmlns="https://www.w3schools.com"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="https://www.w3schools.com banksXSD.xsd">
  <bank>
    <name>Private Bank</name>
    <country>Ukraine</country>
    <type>to the question</type>
    <depositor>Orest Nalyvaiko</depositor>
    <accountID>8775643212345654</accountID>
    <amountOnDeposit>1000.12</amountOnDeposit>
    <profitability>3.5</profitability>
    <timeConstraints>2</timeConstraints>
  </bank>
  <bank>
    <name>Oshad Bank</name>
    <country>Ukraine</country>
    <type>metal</type>
    <depositor>Bogdan Chupa</depositor>
    <accountID>8775632212345654</accountID>
    <amountOnDeposit>10513.46</amountOnDeposit>
    <profitability>5.8</profitability>
    <timeConstraints>5</timeConstraints>
  </bank>
</banks>
